# Generated by Django 6.1.1 on 2026-10-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Biography', 'Biography'), ('History', 'History'), ('Self-Help', 'Self-Help')], max_length=200),
        ),
    ]
